config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  get '/products/listing', to: "products#listing", as: :products_listing 
  resources :products
  resources :categories 
end

app/models/category.rb
class Category < ActiveRecord::Base 
  has_many :products 
end 

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category 

  self.per_page = 3

  def self.search(keyword, page)
    products = all.paginate(page: page)
    if keyword
      keyword = "%#{keyword}%"
      products = products.joins(:category).where(
        'products.name LIKE ? OR categories.name LIKE ?', 
        keyword, keyword 
      )
    else
      products
    end 
  end 

  def self.sort(column, direction, page)
    order("#{column} #{direction}").paginate(page: page)
  end 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 
  before_action :set_category, only: [:show, :update, :destroy, :edit]

  def index 
    @categories = Category.all 
  end 

  def new 
    @category = Category.new 
  end 

  def show 
  end 

  def edit 
  end 

  def create 
    @category = Category.new(category_params)

    if @category.save 
      redirect_to @category 
    else
      render :new  
    end 
  end 

  def update 
    if @category.update(category_params)
      redirect_to @category 
    else 
      render :edit 
    end 
  end 

  def destroy 
    @category.destroy 

    redirect_to categories_url 
  end 

  private 

  def set_category 
    @category = Category.find(params[:id])
  end 
  def category_params 
    params.require(:category).permit(:name)
  end 
end 

app/controllers/products_controller.rb
class ProductsController < ApplicationController 
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def listing
    @listings = Product.all 
  end 

  def index 
    if params[:sort]
      @products = Product.sort(params[:sort], params[:direction], params[:page])
    else 
     @products = Product.search(params[:search], params[:page]) 
    end  
  end 

  def show 
  end 

  def edit 
  end 

  def update 
    if @product.update(product_params) 
      redirect_to @product 
    else
      render :edit 
    end 
  end 

  def new 
    @product = Product.new 
  end 

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product 
    else 
      render :new 
    end 
  end 

  def destroy 
    @product.destroy 

    redirect_to products_url 
  end 

  private 

  def set_product 
    @product = Product.find(params[:id])
  end 

  def product_params 
    params.require(:product).permit(:name, :price, :category_id, 
      :search, :page, :image_url, :description)
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    direction = if column == params[:sort] && params[:direction] == "asc"
                  "desc"
                else 
                  "asc"
                end 
                
    link_to column.titleize, sort: column, direction: direction  
  end 
end

app/views/categories/edit.html.erb
<%= render 'categories/partials/form' %> 

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <h2>Categories Listing</h2>
        <table class="table table-bordered" id="test">
        <thead>
            <tr>
                <th>Name</th>
                <th colspan="2"></th>
            </tr>
        </thead>
        <tbody>
          <%= render partial: 'categories/partials/category', collection: @categories %> 
        </tbody>
        </table>
  </div>
</div>

<%= link_to 'Create New Category', new_category_path %> 

app/views/categories/new.html.erb
<%= render 'categories/partials/form' %> 

app/views/categories/partials/_category.html.erb
<tr>
    <td><%= category.name %></td>
    <td> 
      <%= link_to edit_category_path(category), class: "btn btn-warning" do %> 
          <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
    </td>
    <td> 
      <%= link_to category, method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure?"} do %> 
          <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    </td>
  </tr>

app/views/categories/partials/_form.html.erb
<div class="col-md-8">
  <%= form_for(@category, role: "form") do |f| %> 
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit nil, class: "btn btn-success" %> 
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="field">
  <p>Name: <%= @category.name %></p>

  <%= link_to "Products", root_path %> 
</div>

app/views/layouts/_top_nav_bar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Sabo Market</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Home", products_path %></a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "All", products_listing_path %></li>
          <li><%= link_to "Add New", new_product_path %></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "All", categories_path %></li>
          <li><%= link_to "Add Category", new_category_path %></li>
        </ul>
      </li>
    </ul>
    <div class="col-sm-3 col-md-3">
            
    <%= form_tag products_path, method: :get, id: "search-form", 
                                role: "search", class: "navbar-form" do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], 
                            placeholder: "Enter a keyword", size: 30, 
                            class: "form-control input-mysize" %> 
        <div class="input-group-btn">                        
          <%= button_tag(name: nil, type: "submit", class: "btn btn-success") do %>
              <i class="glyphicon glyphicon-search"></i> 
          <% end %>
        </div>
      </div>
    <% end %>

    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> <span class="badge">5</span></a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Simon <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Edit Profile</a></li>
          <li><a href="#">Settings</a></li>
          <li class="divider"></li>
          <li><a href="#">Logout</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inventory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <style>
    .input-mysize { width: 250px }
    .btn-product{
  width: 100%;
}
  </style>

<!-- Product css -->
  <style>
    
    h4{
      font-weight: 600;
  }
  p{
    font-size: 12px;
    margin-top: 5px;
  }
  .price{
    font-size: 30px;
      margin: 0 auto;
      color: #333;
  }
  .right{
    float:right;
    border-bottom: 2px solid #4B8E4B;
  }
  .thumbnail{
    opacity:0.70;
    -webkit-transition: all 0.5s; 
    transition: all 0.5s;
  }
  .thumbnail:hover{
    opacity:1.00;
    box-shadow: 0px 0px 10px #4bc6ff;
  }
  .line{
    margin-bottom: 5px;
  }
  @media screen and (max-width: 770px) {
    .right{
      float:left;
      width: 100%;
    }
  }


  </style>
</head>


<body>


<%= render 'layouts/top_nav_bar' %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/products/edit.html.erb
<%= render 'products/partials/form' %> 

app/views/products/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= render partial: 'products/partials/product', collection: @products %> 
      </div>
  </div>

  <%= will_paginate @products %>
</div>

app/views/products/listing.html.erb
<div class="container">
  <div class="row">
    <h2>Products Listing</h2>
        <table class="table table-bordered" id="test">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Image URL</th>
                <th>Category</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
        <%= render partial: 'products/partials/listing', collection: @listings %>
        </tbody>
        </table>
  </div>
</div>

app/views/products/new.html.erb
<%= render 'products/partials/form' %> 

app/views/products/partials/_form.html.erb
<div class="col-md-8">
  <%= form_for(@product, role: "form") do |f| %> 
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :price %> 
      <%= f.number_field :price, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :image_url %> 
      <%= f.text_field :image_url, class: "form-control" %> 
    </div>
    
    <div class="form-group">
      <%= f.label :category %>
      <%= f.collection_select :category_id, Category.all, :id, :name, {}, class: "form-control" %> 
    </div>
    
    <%= f.submit nil, class: "btn btn-success" %> 
  <% end %>
</div>

app/views/products/partials/_listing.html.erb
 <tr>
                <td><%= listing.name %></td>
                <td><%= listing.description %></td>
                <td><%= listing.price %></td>
                <td><%= listing.image_url %></td>
                <td><%= listing.category.name %></td>
                <td> 
                  <%= link_to product_path(listing), class: "btn btn-info" do %> 
                      <span class="glyphicon glyphicon-eye-open"></span>
                  <% end %>
                </td>
                <td> 
                  <%= link_to edit_product_path(listing), class: "btn btn-warning" do %> 
                      <span class="glyphicon glyphicon-pencil"></span>
                  <% end %>
                </td>
                <td> 
                  <%= link_to listing, method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure?"} do %> 
                      <span class="glyphicon glyphicon-trash"></span>
                  <% end %>
                </td>
            </tr>

app/views/products/partials/_product.html.erb
<div class="col-sm-6 col-md-4">
        <div class="thumbnail" >
          <h4 class="text-center"><span class="label label-info"><%= product.category.name%></span></h4>
          <img src="<%= product.image_url %>" class="img-responsive"/><div class="caption">
            <div class="row">
              <div class="col-md-6 col-xs-6">
                <h3><%= product.name %></h3>
              </div>
              <div class="col-md-6 col-xs-6 price">
                <h3>
                <label>$<%= product.price %></label></h3>
              </div>
            </div>
            <p><%= product.description || "No description yet"%></p>
            <div class="row">
              <div class="col-md-6">
                <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-thumbs-up"></span> Like</a> 
              </div>
              <div class="col-md-6">
                <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> Buy</a></div>
            </div>

            <p> </p>
          </div>
        </div>
    </div>

app/views/products/show.html.erb
<div class="field" id='#product-info'>
  <p>Name: <%= @product.name %></p>
  <p>Price: $<%= @product.price %></p>
  <p>Category: <%= @product.category.name %></p>

  <%= link_to "Products", products_path %> 
</div>